### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by YarnikeyZ** [srilakshmikanthanp/libfiglet#1]
What i do:
```
> g++ Test.cpp -o Test && ./Test
```
What i get:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  flf2a not found !
[1]    5288 abort (core dumped)  ./Test
```
Code:
```
#include <iostream>
#include "srilakshmikanthanp/Figlet.hpp"

using namespace srilakshmikanthanp;

int main()
{
    Figlet figlet(FigletFont::make("Fonts/Standard.flf"), Smushed::make());
    std::cout << figlet("Hello, C++");
    return 0;
}
```

**Comment by srilakshmikanthanp** [comment]
Hey, thanks for raising issue now I added the file not found error could you please run the same program but with also with the Fonts folder available,

~~~cpp
#include <iostream>
#include "./Figlet.hpp"

using namespace srilakshmikanthanp;

int main()
{
    Figlet figlet(FigletFont::make("./Fonts/Standard.flf"), Smushed::make());
    std::cout << figlet("Hello, C++");
    return 0;
}
~~~

Assuming the [Fonts](https://github.com/srilakshmikanthanp/Figlet/tree/master/Fonts) folder will present in current working directory

**Comment by YarnikeyZ** [comment]
![terminate called after throwing an instance of 'std::runtime_error'](https://user-images.githubusercontent.com/83335375/157658493-912c612a-c833-4d92-b983-11ab663f0316.png)
**1.** When Fonts folder **is not in** current working directory;
**2.** When Fonts folder **is in** current working directory.
_I think everything is working as it should now._
_Thanks!_

**Comment by srilakshmikanthanp** [comment]
Yeah! Just pass the path to font or stringstream to FigletFont::make
