### ISSUE TITLE
Attempts to use + to format strings with Figlet output

### ISSUE THREAD

**Issue by YarnikeyZ** [srilakshmikanthanp/libfiglet#2]
(_day, month, year is just a strings_)

I tried to format srings with **+** like that:
`cout << figlet("[").getString() + " " + figlet(day) + " " + figlet(".") + " " + figlet(month) + " " + figlet(".") + " " + figlet(year) + " " + figlet("]") << endl;`
and that didn't worked.

Then i remembered about .getString() and tried:
`cout << figlet("[").getString() + " " + figlet(day).getString() + " " + figlet(".").getString() + " " + figlet(month).getString() + " " + figlet(".").getString() + " " + figlet(year).getString() + " " + figlet("]").getString() << endl;`
but that didn't worked again.

And i think i can't show error code after first and second attempt because they **to big**.

_How can i do it properly?_

**Comment by srilakshmikanthanp** [comment]
Can you please elaborate what you are trying to achieve with a sample I/O ?

**Comment by YarnikeyZ** [comment]
![for_githb](https://user-images.githubusercontent.com/83335375/157703277-7f73e70a-f6e2-4113-b293-114042909604.png)
**1.** What i want to get (_without passing a spaces to a figlet func_)
**2.** What i getting  (_with passing a spaces to a figlet func_)

**Comment by srilakshmikanthanp** [comment]
Currently adding two figlet is not possible but if you want custom space you can inherit `FigletFont`,

~~~c++
#include <iostream>
#include "../include/srilakshmikanthanp/Figlet.hpp"

using namespace srilakshmikanthanp;

class CustomSpaceFont : public FigletFont 
{
public:
    using FigletFont::BasicFigletFont;

    virtual Figc_type getFigc(char_type ch) const override
    {
        if(ch == ' ') 
        {
            Figc_type fig = Figc_type();
            for(int i = 0; i < this->getHeight(); i++)
            {
                string_type str = "";
                str.push_back(this->getHardBlank());
                str += "";
                str.push_back(this->getHardBlank());
                fig.push_back(str);
            }
            return fig;
        }

        return FigletFont::getFigc(ch);
    }
};

int main()
{
    Figlet figlet(std::make_shared<CustomSpaceFont>("../assets/fonts/Standard.flf"), Smushed::make());
    auto fig = figlet("[ 03 . 10 . 2022 ]");
    std::cout << fig << std::endl;
    return 0;
}
~~~

And with last commit i changed the `figlet("")` to return string directly :)
