### ISSUE TITLE
Style not supported even with font files bundled with library

### ISSUE THREAD

**Issue by nsh07** [srilakshmikanthanp/libfiglet#3]
Many font files included with this library make it throw a "style not supported" error even though the Figlet program can easily handle them, for example the `USA Flag.flf` or the `3d.flf` font files. I'm using the test code provided in this repo:
```cpp
#include <iostream>
#include "../include/srilakshmikanthanp/Figlet.hpp"

using namespace srilakshmikanthanp;

int main()
{
    Figlet figlet(FigletFont::make("../assets/fonts/USA Flag.flf"), Smushed::make());
    std::cout << figlet("Hello, C++");
    return 0;
}
```
This code exits with the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  style not supported
Aborted (core dumped)
```
But the figlet program can handle it:
```
$ figlet -s -f "../assets/fonts/USA Flag.flf" Hello, C++
 :::  === :::===== :::      :::      :::====           :::=====   ===     ===  
 :::  === :::      :::      :::      :::  ===          :::        ===     ===  
 ======== ======   ===      ===      ===  ===          ===      ======= =======
 ===  === ===      ===      ===      ===  ===  ==      ===        ===     ===  
 ===  === ======== ======== ========  ======   ==       =======   ===     ===  
                                              ==                               
```
Please fix this issue.
Thanks in advance!

**Comment by srilakshmikanthanp** [comment]
The header of the font

~~~flf
flf2a$ 6 5 18 -1 19
~~~

Asper in [docs](http://www.jave.de/figlet/figfont.html) old_layout the font only supports full width, Note: It seems like the figlet also uses full width. So you can't use Kerning or smushed for this font.

**Comment by nsh07** [comment]
Hey, thanks I get it now

Is there a way to use full width in this library? I tried using `FullWidth::make()` but it segfaults

Edit: Okay `FullWidth::make()` is working just fine, I did something wrong last time. Thanks for the help! Pretty awesome library you've made

**Comment by nsh07** [comment]
Closing this issue

**Comment by srilakshmikanthanp** [comment]
Thank you 😄
