### ISSUE TITLE
could it read font from memory?

### ISSUE THREAD

**Issue by fgfxf** [srilakshmikanthanp/libfiglet#7]
i want my exe/ELF release in only one file.

**Comment by srilakshmikanthanp** [comment]
Yes, Just pass an istream with, https://github.com/srilakshmikanthanp/libfiglet/blob/7b41272dae70c20d4f26d4c6b80c019b225f7ae6/src/srilakshmikanthanp/fonts/fonts.hpp#L334 Let me now if you face any problem :)

**Comment by fgfxf** [comment]
thank you，all ok
